[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
serde = { version= "1", features=["derive"] }
serde_json = "1"
rand = "0.8.4"
rust-hashcash = "0.1"
md5 = "0.7.0"